# Generated by Django 4.2.4 on 2025-10-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0017_pet_cliente_pet_pelagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('A', 'Agendada'), ('F', 'Finalizada'), ('C', 'Cancelada'), ('L', 'Avaliada'), ('I', 'Iniciada')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='pet_cliente',
            name='Pet_Sexo',
            field=models.CharField(choices=[('I', 'Indefindio'), ('M', 'Macho'), ('F', 'Femea')], default='I', max_length=1),
        ),
    ]
