# Generated by Django 4.2.4 on 2026-04-18 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0018_alter_consulta_status_alter_pet_cliente_pet_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('R', 'Retirada'), ('E', 'Entrega')], max_length=10)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('I', 'Iniciada'), ('F', 'Finalizada'), ('C', 'Cancelada')], default='A', max_length=1)),
                ('link', models.URLField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('Pet_Cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.pet_cliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
