# Generated by Django 4.2.4 on 2026-04-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0020_entregaretirada_trajetoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaretirada',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregaretirada',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
