# Generated by Django 4.2.4 on 2026-05-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0022_local_petlocalassignment_petmonitorhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='petlocalassignment',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_local'),
        ),
        migrations.AddField(
            model_name='petlocalassignment',
            name='Video',
            field=models.ImageField(blank=True, null=True, upload_to='Hospitalization/Videos'),
        ),
    ]
