# Generated by Django 4.2.4 on 2026-05-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0023_petlocalassignment_foto_petlocalassignment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmonitorhistory',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
