# Generated by Django 4.2.4 on 2026-04-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='id_mn_Esquerdo',
            field=models.CharField(choices=[('1', 'Ativo'), ('0', 'Inativo')], default='1', max_length=1),
        ),
    ]
